// Code generated by service_registration.sh; DO NOT EDIT.

package services

import (
	servicemanager "github.com/psyb0t/pr0xteus/internal/pkg/service-manager"
	pr0xteus "github.com/psyb0t/pr0xteus/internal/pkg/services/pr0xteus"
)

func Init() {
	sm := servicemanager.GetInstance()

	sm.Register(pr0xteus.ServiceName, func() (servicemanager.Service, error) {
		return pr0xteus.New()
	})

}
